### ISSUE TITLE
Will there be any continuation of this project?

### ISSUE THREAD

**Issue by ghost** [michaelforney/wld#19]
It seems like it is abondaned since 2019. Nothing major has changed since then. GTK apps work at least but that's about as far as you can come without encountering tons of warnings/errors.

For example: Most apps depend on libEGL (even QT does). And every time it gives 3 warnings.
`
libEGL warning: failed to get driver name for fd 0
libEGL warning: MESA-LOADER: failed to retrieve device information
libEGL warning: failed to get driver name for fd 0
`
I wanted to add more examples of apps that didn't work. But they all come to the same point. This project is out of date. Nothing works as intended.

Chromium doesn't even work as intended (Which is a minimum requirement to ask for) because GPU acceleration is kind of broken. Firefox doesn't even attempt to render. Black screen. Firefox can open new tabs and stuff but no rendering.

I really like this project as it's snappy on every machine I've tried it on (As long as you use your outdated apps). I know you do this for free and that this might be too much too ask for, but please. Attempt to update this.

**Comment by michaelforney** [comment]
> It seems like it is abondaned since 2019. Nothing major has changed since then. GTK apps work at least but that's about as far as you can come without encountering tons of warnings/errors.

It's been working fine for me. Ideally I'd like to support more GPUs with hardware support and add a vulkan backend, and some of those ideas are started in [libblit](https://git.sr.ht/~mcf/libblit), but that project still has a long way to go, and modern GPU drivers are extremely complex, so I'm way out of my depth.

> For example: Most apps depend on libEGL (even QT does). And every time it gives 3 warnings. `libEGL warning: failed to get driver name for fd 0 libEGL warning: MESA-LOADER: failed to retrieve device information libEGL warning: failed to get driver name for fd 0` I wanted to add more examples of apps that didn't work. But they all come to the same point. This project is out of date. Nothing works as intended.

Qt apps work for me just fine. Are you sure those warnings are the actual cause of your problems? I suggest you do some debugging and find out what's not working and why.

> Chromium doesn't even work as intended (Which is a minimum requirement to ask for) because GPU acceleration is kind of broken. Firefox doesn't even attempt to render. Black screen. Firefox can open new tabs and stuff but no rendering.

Chrome also works just fine for me. Firefox not working has nothing to do with wld, but the wl_subsurface protocol in swc not being fully implemented.

> I really like this project as it's snappy on every machine I've tried it on (As long as you use your outdated apps). I know you do this for free and that this might be too much too ask for, but please. Attempt to update this.

Feel free to send me your patches.

P.S. entitled comments like these make me less motivated to work on these projects
